# Fitness Builder UI - Docker Compose
# 
# Requirements:
# - Easy deployment with environment configuration
# - Portainer-compatible setup
# - Environment variables for API endpoints
# 
# Flow:
# - Build and run the UI container
# - Configure API endpoints via environment variables
# - Expose port 8888 for web access

version: '3.8'

services:
  fitness-builder-ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Build-time environment variables - update these for your deployment
        - VITE_API_BASE_URL_LOCAL=${VITE_API_BASE_URL_LOCAL:-http://localhost:8000}
        - VITE_API_BASE_URL_NETWORK=${VITE_API_BASE_URL_NETWORK:-http://192.168.0.47:8000}
        - VITE_API_BASE_URL_TAILSCALE=${VITE_API_BASE_URL_TAILSCALE:-http://100.106.26.92:8000}
    container_name: fitness-builder-ui
    ports:
      - "8888:8888"
    environment:
      # Runtime environment variables - these override build-time args
      # Set these in your deployment environment or .env file
      - VITE_API_BASE_URL_LOCAL=${VITE_API_BASE_URL_LOCAL:-http://localhost:8000}
      - VITE_API_BASE_URL_NETWORK=${VITE_API_BASE_URL_NETWORK:-http://192.168.0.47:8000}
      - VITE_API_BASE_URL_TAILSCALE=${VITE_API_BASE_URL_TAILSCALE:-http://100.106.26.92:8000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8888/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 